### ISSUE TITLE
building on Python 3.6 requires python 2.7 headers

### ISSUE THREAD

**Issue by jmgnc** [ChargePoint/pydnp3#4]
All of the includes of Python.h include python2.7 in the path.  This means that even when you're compiling on Python 3.6, you need to have python2.7-dev installed.

To reproduce, if you have docker, launch a python 3.6 container:
```
docker run -it --rm python:3.6 bash
```

Then in the prompt that follows run:
```
apt-get update
apt-get install -y cmake

pip install --no-binary :all: pydnp3
```

and after a bit, you'll see the following error:
```
    [ 99%] Building CXX object CMakeFiles/pydnp3.dir/src/pydnp3.cpp.o            
    In file included from /tmp/pip-install-ekdqm24w/pydnp3/src/AllHeaders.h:32:0,
                     from /tmp/pip-install-ekdqm24w/pydnp3/src/pydnp3.cpp:38:     
    /tmp/pip-install-ekdqm24w/pydnp3/src/asiodnp3/ConsoleLogger.h:32:30: fatal error: python2.7/Python.h: No such file or directory
     #include <python2.7/Python.h>                                              
```

As we are building on 3.6, there shouldn't be any need for Python 2.7 to be installed.
```
root@52b67bd86f9f:/# pip --version
pip 18.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
```

If you add python2.7-dev to the cmake install line above, it will complete building.

**Comment by 0xSn4k3000** [comment]
This is not fixed yet.
