### ISSUE TITLE
MinGW-x64 Compile error

### ISSUE THREAD

**Issue by taegyo** [ChargePoint/pydnp3#9]
i compiled on windows 10 using mingw-x64 compiler.
but, in link step failed.

# cmake -G "MinGW Makefiles"
# mingw32-make

last error message:
[100%] Linking CXX shared module pydnp3.cp37-win_amd64.pyd
C:\Users\pcf\AppData\Local\Temp\ccx9x76d.ltrans14.ltrans.o:<artificial>:(.text+0xa3b1): undefined reference to `asiopal::TimeConversions::Convert(std::chrono::time_point<asiopal::SteadyClockWindows, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> > > const&)'
deps/dnp3/libasiopal.a(Executor.cpp.obj):Executor.cpp:(.text+0x145): undefined reference to `asiopal::TimeConversions::Convert(std::chrono::time_point<asiopal::SteadyClockWindows, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> > > const&)'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [CMakeFiles\pydnp3.dir\build.make:93: pydnp3.cp37-win_amd64.pyd] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:75: CMakeFiles/pydnp3.dir/all] Error 2
mingw32-make: *** [Makefile:129: all] Error 2

please, help me.

**Comment by anhnguyen-cpi** [comment]
I'm not familiar with MinGW-x64 compiler. However, the build requires at least 8Gb free memory. You might want to check to make sure you have enough memory.

**Comment by taegyo** [comment]
yes, my memory is 16GB. it's enough memory.

**Comment by taegyo** [comment]
it's solved. but import pydnp3 not found dll...haha
